# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20171024_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_choose',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
